### ISSUE TITLE
open Api를 통한 데이터 수집 시간이 너무 오래 걸림

### ISSUE THREAD

**Issue by DongDongShin** [library-search-machine/read_open_api#1]
이것을 해결할 방법을 찾아봅시다.!!

**Comment by Lee1231234** [comment]
정보나루에는 장서/대출을 csv파일로 달마다 저장해두고 있습니다 이것을 데이터베이스로 옮기면 어떨까요?

**Comment by scarlet0o0** [comment]
csv 파일이 엄청 많은데 그걸 다 다운받고 해야 되나요?

**Comment by DongDongShin** [comment]
> 정보나루에는 장서/대출을 csv파일로 달마다 저장해두고 있습니다 이것을 데이터베이스로 옮기면 어떨까요?

좋을 것 같습니다.  만약 이런 차용한다면 .csv파일을 db로 저장하는 방법을 찾으면 좋겠네요

**Comment by DongDongShin** [comment]
> csv 파일이 엄청 많은데 그걸 다 다운받고 해야 되나요?

test

**Comment by Lee1231234** [comment]
> csv 파일이 엄청 많은데 그걸 다 다운받고 해야 되나요?

실제로 openapi로 6만개 정도의 데이터를 받으면 33분이라는 시간을 데이터 통신에만 소비합니다.. 
이것을 csv파일로 받으면 DB에 저장하는 시간을 제외하고 많은 시간을 절약할수 있습니다

**Comment by Lee1231234** [comment]
> 좋을 것 같습니다. 만약 이런 차용한다면 .csv파일을 db로 저장하는 방법을 찾으면 좋겠네요


https://bibi6666667.tistory.com/200
csv파일을 자바로 여는방법은 이걸 참고하면 좋겠네요

**Comment by Lee1231234** [comment]
실제로 6만건정도의 데이터를 OpenApi로 받아서 DB에 저장하는데 75분정도가 걸렸습니다. 
csv파일로 DB에 저장할때 그것보다 적게 걸린다면 csv를 사용하고  더 나은 방법이 있다면 알려주세요

**Comment by Lee1231234** [comment]
실제로 csv파일을 통해서 500만건의 데이터를 집어넣을때 평균적으로 1분 30초정도 걸리는것으로 나타났습니다. 

앞으로 데이터를 집어넣을때는 openApi가 아닌 csv파일로 집어넣죠
