### ISSUE TITLE
json object를 받고 JSONArray로 casting 하는데 null값이 발행합니다

### ISSUE THREAD

**Issue by DongDongShin** [library-search-machine/read_open_api#2]
![test](https://user-images.githubusercontent.com/100353794/191008851-48e8ff36-5b90-49c2-8e6f-1e6cb907fa51.PNG)
![주작2](https://user-images.githubusercontent.com/100353794/191009455-4498a55f-2ee2-4693-8198-de22adbabd64.PNG)
혹시 해결법을 알 수 있을까요??

**Comment by Lee1231234** [comment]
저도 같은 문제가 있었습니다.
![image](https://user-images.githubusercontent.com/32947395/191009252-5daff7df-8760-4c5d-b141-e9b58f096928.png)
저 같은 경우에는 JSONArray에서 key값이 doc이 아닌 i로 출력이 되는것을 확인할수 있었습니다.

동하님 같은 경우에도 비슷한 문제이지 않을까요?

**Comment by DongDongShin** [comment]
분명 데이터 배열의 key값이 docs인데 왜 null이 나오는지 모르겠네요...

**Comment by Lee1231234** [comment]
result.toString() 부분이 잘못된거 같습니다 "response"를 파싱해야하는데 실제로 파싱하는게 아닌것같아요 
result.toString()을 "response"로 바꿔보시겠어요?

**Comment by scarlet0o0** [comment]
`result.toString()` 부분이 잘못된거 같습니다 
"response"를 파싱해야하는데 실제로 파싱하는게 아닌것같아요
`result.toString()`을 `response`로 바꿔보시겠어요?

**Comment by DongDongShin** [comment]
아... 해결했습니다. 감사합니다😀
