### ISSUE TITLE
csv 파일을 받을때 한글이 깨져서 나옵니다.

### ISSUE THREAD

**Issue by Lee1231234** [library-search-machine/read_open_api#3]
어떻게 하면 좋을까요?
![깨짐](https://user-images.githubusercontent.com/100353794/191240874-92876675-a3d9-4652-b18a-b0d981587bf5.PNG)

**Comment by scarlet0o0** [comment]
찾아보니 [csv 한글깨짐](https://mainia.tistory.com/6658) 문제인거 같은데
utf-8로 변경해보시겠어요?

**Comment by DongDongShin** [comment]
> 어떻게 하면 좋을까요? 

저도 같은 오류가 나왔는데 파일 인코딩 형식 바꾸니 정상적으로 동작되더라구요 참고하실 링크 첨부하겠습니다.
https://kggo.tistory.com/155

**Comment by Lee1231234** [comment]
오호 해결됬습니다. 그런데 또다른 문제가 생기네요...

`String[] lineArr = line.split(","); // 파일의 한 줄을 ,로 나누어 배열에 저장 후 리스트로 변환한다.`
이렇게  코드를 ,으로 나누면 실제 데이터와 다르게 나뉘는걸 볼수있습니다. 아마 다른 특수한 구분자를 사용해야 안전하게 토큰분리를 할수있을것 같아요.

**Comment by Lee1231234** [comment]
[엑셀 csv파일 구분자 변경](https://github.com/library-search-machine/read_open_api/issues/3#issuecomment-1252190112)

이걸 통해서 해결하면 될것같아요

**Comment by DongDongShin** [comment]
> 이걸 통해서 해결하면 될것같아요

csv파일 보니깐 ,로 데이터를 나누면 데이터의 파싱이 잘 안되네요.. 한번 제가 찾아보았는데 저희 local 컴퓨터의 데이터 구분기호를 |로 설정하면 될것같습니다  그래야 csv가 잘 파싱이 되는것 같습니다.! 참고 사이트 첨부하겠습니다.
https://learnandcreate.tistory.com/560
